# Generated by Django 5.1.4 on 2024-12-24 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_profile_major_profile_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='usual_size',
            field=models.CharField(blank=True, choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], max_length=2, null=True),
        ),
    ]
