# Generated by Django 5.1.4 on 2024-12-27 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_follow_follower_alter_follow_following'),
        ('products', '0011_alter_product_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cart',
            field=models.ManyToManyField(blank=True, related_name='liked_by', to='products.product'),
        ),
    ]
