# Generated by Django 5.1.4 on 2024-12-23 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='상품명')),
                ('description', models.TextField(verbose_name='설명')),
                ('price', models.IntegerField(verbose_name='가격')),
                ('category', models.CharField(choices=[('uniform', '교복'), ('book', '교재'), ('supply', '학용품')], max_length=20, verbose_name='카테고리')),
                ('uniform_type', models.CharField(blank=True, choices=[('winter', '동복'), ('summer', '하복'), ('pe', '체육복'), ('casual', '생활복'), ('accessory', '액세서리')], max_length=10, verbose_name='교복 종류')),
                ('condition', models.CharField(choices=[('excellent', '아주 좋아요'), ('great', '훌륭해요'), ('vert-good', '좋아요'), ('good', '나쁘지 않아요')], max_length=10, verbose_name='상태')),
                ('image', models.ImageField(upload_to='products/', verbose_name='대표이미지')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('view_count', models.IntegerField(default=0, verbose_name='조회수')),
                ('size', models.CharField(blank=True, choices=[('FREE', 'FREE'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], default='FREE', max_length=4, verbose_name='사이즈')),
                ('trade_type', models.CharField(blank=True, choices=[('direct', '직거래'), ('delivery', '택배거래'), ('both', '협의')], default='both', max_length=10, verbose_name='거래방법')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='판매자')),
            ],
            options={
                'verbose_name': '상품',
                'verbose_name_plural': '상품들',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'unique_together': {('user', 'product')},
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='내용')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='평점')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '리뷰',
                'verbose_name_plural': '리뷰들',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'product')},
            },
        ),
    ]
