# Generated by Django 5.1.4 on 2024-12-26 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_cartitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='문의내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('is_answered', models.BooleanField(default=False, verbose_name='답변여부')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='답변내용')),
                ('answered_at', models.DateTimeField(blank=True, null=True, verbose_name='답변일')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '문의',
                'verbose_name_plural': '문의들',
                'ordering': ['-created_at'],
            },
        ),
    ]
