# Generated by Django 5.1.4 on 2024-12-26 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_sold',
            field=models.BooleanField(default=False, verbose_name='판매완료'),
        ),
        migrations.AddField(
            model_name='product',
            name='sold_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='판매완료일'),
        ),
    ]
